version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: voty-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - voty-network
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "rootpassword", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    # pas de profile -> démarre par défaut (pratique pour le dev local DB-only)

  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: voty-server
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongo:27017/voty?authSource=admin
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
      - CLIENT_URL=http://localhost
    ports:
      - "3000:3000"
    networks:
      - voty-network
    profiles: ["app"]

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/api
    container_name: voty-client
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - voty-network
    profiles: ["app"]

networks:
  voty-network:
    driver: bridge

volumes:
  mongo-data: